import { Injectable } from '@nestjs/common';
import { PressContext, SecurityClassification } from './interfaces/press-context.interface';

@Injectable()
export class MotifEngine {

    /**
     * Resolves the visual motif (Branding, Headers, Footers) based on context.
     */
    resolveMotif(context: PressContext) {
        return {
            header: this.getHeader(context),
            footer: this.getFooter(context),
            watermark: this.getWatermark(context),
            styles: this.getStyles(context),
            securityStamp: this.getSecurityStamp(context)
        };
    }

    private getHeader(context: PressContext) {
        if (context.showLogo === false) return null;

        return {
            bankName: 'Indian Overseas Bank',
            officeName: context.officeName || 'Central Office, Chennai',
            officePhone: context.officePhone || '+91 44 2851 9123',
            officeEmail: context.officeEmail || 'governance@iob.in',
            logoUrl: 'assets/iob-logo.png',
            generatedAt: new Date().toLocaleDateString('en-IN', {
                day: '2-digit', month: 'long', year: 'numeric'
            })
        };
    }

    private getFooter(context: PressContext) {
        return {
            address: context.officeAddress || '763, Anna Salai, Chennai - 600002',
            contact: `Ph: ${context.officePhone || '+91 44 2851 9123'} | Email: ${context.officeEmail || 'governance@iob.in'}`,
            disclaimer: context.classification === 'CONFIDENTIAL'
                ? 'CONFIDENTIAL DOCUMENT - FOR INTERNAL CIRCULATION ONLY'
                : 'Generated by IOBIAN Governance System'
        };
    }

    private getWatermark(context: PressContext) {
        if (context.isDraft) return 'DRAFT';
        if (context.classification === 'CONFIDENTIAL') return 'CONFIDENTIAL';
        return null;
    }

    private getStyles(context: PressContext) {
        const primaryColor = '#1d4ed8'; // IOB Blue
        const dangerColor = '#dc2626'; // Red

        return {
            primaryColor,
            headerColor: context.classification === 'CONFIDENTIAL' ? dangerColor : primaryColor,
            fontFamily: 'Century Gothic, sans-serif'
        };
    }

    private getSecurityStamp(context: PressContext) {
        return {
            generatedAt: new Date().toISOString(),
            classification: context.classification,
            digitalSignaturePlaceholder: '[ Digitally Signed ]'
        };
    }
}
